# Generated by Django 4.2.7 on 2025-07-19 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='system', max_length=255)),
                ('total_items', models.IntegerField(default=0)),
                ('total_units', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('export_file', models.FileField(blank=True, null=True, upload_to='exports/')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('manual', 'Ручная'), ('scheduled', 'По расписанию')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'В процессе'), ('success', 'Успешно'), ('failed', 'Ошибка'), ('partial', 'Частично выполнено')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('warehouse_id', models.CharField(max_length=36)),
                ('warehouse_name', models.CharField(max_length=255)),
                ('excluded_groups', models.JSONField(default=list)),
                ('total_products', models.IntegerField(default=0)),
                ('synced_products', models.IntegerField(default=0)),
                ('failed_products', models.IntegerField(default=0)),
                ('error_details', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('priority', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('production_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sync.productionlist')),
            ],
            options={
                'ordering': ['priority', 'product__article'],
            },
        ),
    ]
