# Generated by Django 4.2.7 on 2025-07-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclog',
            name='current_article',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
