FROM nginx:alpine

# Удаляем конфиг по умолчанию
RUN rm /etc/nginx/conf.d/default.conf

# Копируем наш конфиг
COPY docker/nginx/nginx.prod.conf /etc/nginx/conf.d/

# Создаем папки
RUN mkdir -p /app/static /app/media /app/frontend

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]