# Generated by Django 4.2.7 on 2025-10-22 18:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimplePrintSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'В процессе'), ('success', 'Успешно'), ('failed', 'Ошибка'), ('partial', 'Частично выполнено')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_folders', models.IntegerField(default=0)),
                ('synced_folders', models.IntegerField(default=0)),
                ('total_files', models.IntegerField(default=0)),
                ('synced_files', models.IntegerField(default=0)),
                ('deleted_files', models.IntegerField(default=0)),
                ('error_details', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'SimplePrint Синхронизация',
                'verbose_name_plural': 'SimplePrint Синхронизации',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SimplePrintFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simpleprint_id', models.IntegerField(db_index=True, help_text='ID папки в SimplePrint', unique=True)),
                ('name', models.CharField(help_text='Название папки', max_length=500)),
                ('depth', models.IntegerField(default=0, help_text='Уровень вложенности')),
                ('files_count', models.IntegerField(default=0, help_text='Количество файлов в папке')),
                ('folders_count', models.IntegerField(default=0, help_text='Количество подпапок')),
                ('can_view', models.BooleanField(default=True)),
                ('can_upload', models.BooleanField(default=True)),
                ('can_modify', models.BooleanField(default=True)),
                ('can_download', models.BooleanField(default=True)),
                ('created_at_sp', models.DateTimeField(help_text='Дата создания в SimplePrint')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания в локальной БД')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата обновления в локальной БД')),
                ('last_synced_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата последней синхронизации')),
                ('parent', models.ForeignKey(blank=True, help_text='Родительская папка', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='simpleprint.simpleprintfolder')),
            ],
            options={
                'verbose_name': 'SimplePrint Папка',
                'verbose_name_plural': 'SimplePrint Папки',
                'ordering': ['depth', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SimplePrintFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simpleprint_id', models.CharField(db_index=True, help_text='ID/хэш файла в SimplePrint', max_length=255, unique=True)),
                ('name', models.CharField(help_text='Имя файла', max_length=500)),
                ('ext', models.CharField(blank=True, help_text='Расширение файла', max_length=20)),
                ('file_type', models.CharField(blank=True, help_text='Тип файла (printable, etc)', max_length=50)),
                ('size', models.BigIntegerField(default=0, help_text='Размер файла в байтах')),
                ('zip_printable', models.BooleanField(default=False)),
                ('zip_no_model', models.BooleanField(default=False)),
                ('user_id', models.IntegerField(blank=True, help_text='ID пользователя в SimplePrint', null=True)),
                ('thumbnail', models.IntegerField(default=0, help_text='Наличие миниатюры')),
                ('for_printer_models', models.JSONField(blank=True, default=list, help_text='Модели принтеров')),
                ('for_printers', models.JSONField(blank=True, default=list, help_text='Конкретные принтеры')),
                ('tags', models.JSONField(blank=True, default=dict, help_text='Теги файла (nozzleData, material)')),
                ('print_data', models.JSONField(blank=True, default=dict, help_text='Статистика печати (printsDone, printsCancelled, etc)')),
                ('cost_data', models.JSONField(blank=True, default=dict, help_text='Информация о стоимости')),
                ('gcode_analysis', models.JSONField(blank=True, default=dict, help_text='Детальный анализ G-code')),
                ('custom_fields', models.JSONField(blank=True, default=list, help_text='Пользовательские поля')),
                ('created_at_sp', models.DateTimeField(help_text='Дата создания в SimplePrint')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания в локальной БД')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата обновления в локальной БД')),
                ('last_synced_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата последней синхронизации')),
                ('folder', models.ForeignKey(blank=True, help_text='Папка в которой находится файл', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='simpleprint.simpleprintfolder')),
            ],
            options={
                'verbose_name': 'SimplePrint Файл',
                'verbose_name_plural': 'SimplePrint Файлы',
                'ordering': ['-created_at_sp'],
            },
        ),
        migrations.AddIndex(
            model_name='simpleprintfolder',
            index=models.Index(fields=['parent', 'name'], name='simpleprint_parent__4099f4_idx'),
        ),
        migrations.AddIndex(
            model_name='simpleprintfolder',
            index=models.Index(fields=['simpleprint_id'], name='simpleprint_simplep_1b57c8_idx'),
        ),
        migrations.AddIndex(
            model_name='simpleprintfolder',
            index=models.Index(fields=['last_synced_at'], name='simpleprint_last_sy_745b80_idx'),
        ),
        migrations.AddIndex(
            model_name='simpleprintfile',
            index=models.Index(fields=['folder', 'name'], name='simpleprint_folder__3d8500_idx'),
        ),
        migrations.AddIndex(
            model_name='simpleprintfile',
            index=models.Index(fields=['simpleprint_id'], name='simpleprint_simplep_1f138f_idx'),
        ),
        migrations.AddIndex(
            model_name='simpleprintfile',
            index=models.Index(fields=['file_type'], name='simpleprint_file_ty_dca835_idx'),
        ),
        migrations.AddIndex(
            model_name='simpleprintfile',
            index=models.Index(fields=['last_synced_at'], name='simpleprint_last_sy_61273b_idx'),
        ),
        migrations.AddIndex(
            model_name='simpleprintfile',
            index=models.Index(fields=['-created_at_sp'], name='simpleprint_created_20777b_idx'),
        ),
    ]
