# Generated by Django 4.2.7 on 2025-10-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleprint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimplePrintWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('file_created', 'Файл создан'), ('file_updated', 'Файл обновлен'), ('file_deleted', 'Файл удален'), ('folder_created', 'Папка создана'), ('folder_deleted', 'Папка удалена'), ('unknown', 'Неизвестное событие')], max_length=50)),
                ('payload', models.JSONField(help_text='Полные данные webhook')),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SimplePrint Webhook Event',
                'verbose_name_plural': 'SimplePrint Webhook Events',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['event_type', '-received_at'], name='simpleprint_event_t_5160e7_idx'), models.Index(fields=['processed', '-received_at'], name='simpleprint_process_c59afa_idx')],
            },
        ),
    ]
