# Generated by Django 4.2.7 on 2025-10-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleprint', '0002_simpleprintwebhookevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_id', models.CharField(db_index=True, help_text='SimplePrint ID принтера', max_length=50)),
                ('printer_name', models.CharField(help_text='Имя принтера (P1S-2, P1S-3, etc.)', max_length=100)),
                ('state', models.CharField(choices=[('printing', 'Печатает'), ('idle', 'Ожидание'), ('offline', 'Оффлайн'), ('paused', 'Пауза'), ('error', 'Ошибка')], help_text='Состояние принтера', max_length=20)),
                ('online', models.BooleanField(default=True, help_text='Принтер онлайн')),
                ('job_id', models.CharField(blank=True, help_text='ID задания', max_length=50, null=True)),
                ('job_file', models.CharField(blank=True, help_text='Имя файла задания', max_length=500, null=True)),
                ('percentage', models.IntegerField(default=0, help_text='Процент выполнения (0-100)')),
                ('current_layer', models.IntegerField(default=0, help_text='Текущий слой')),
                ('max_layer', models.IntegerField(default=0, help_text='Максимальный слой')),
                ('elapsed_time', models.IntegerField(default=0, help_text='Прошло времени (секунды)')),
                ('temperature_nozzle', models.IntegerField(blank=True, help_text='Температура сопла (°C)', null=True)),
                ('temperature_bed', models.IntegerField(blank=True, help_text='Температура стола (°C)', null=True)),
                ('temperature_ambient', models.IntegerField(blank=True, help_text='Температура окружающей среды (°C)', null=True)),
                ('job_start_time', models.DateTimeField(blank=True, help_text='Расчетное время начала задания', null=True)),
                ('job_end_time_estimate', models.DateTimeField(blank=True, help_text='Расчетное время окончания', null=True)),
                ('idle_since', models.DateTimeField(blank=True, help_text='В состоянии ожидания с', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Время создания снимка')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Время обновления снимка')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Полные данные от API')),
            ],
            options={
                'verbose_name': 'SimplePrint Printer Snapshot',
                'verbose_name_plural': 'SimplePrint Printer Snapshots',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['printer_id', '-created_at'], name='simpleprint_printer_d9917d_idx'), models.Index(fields=['state', '-created_at'], name='simpleprint_state_af86e8_idx'), models.Index(fields=['printer_name'], name='simpleprint_printer_72f8dc_idx')],
            },
        ),
    ]
