# Generated by Django 4.2.7 on 2025-10-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleprint', '0003_printersnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printersnapshot',
            name='current_layer',
            field=models.IntegerField(blank=True, default=0, help_text='Текущий слой', null=True),
        ),
        migrations.AlterField(
            model_name='printersnapshot',
            name='max_layer',
            field=models.IntegerField(blank=True, default=0, help_text='Максимальный слой', null=True),
        ),
        migrations.CreateModel(
            name='PrintQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_id', models.CharField(db_index=True, help_text='ID очереди в SimplePrint', max_length=50, unique=True)),
                ('printer_id', models.CharField(db_index=True, help_text='ID принтера', max_length=50)),
                ('printer_name', models.CharField(help_text='Имя принтера', max_length=100)),
                ('file_id', models.CharField(help_text='ID файла в SimplePrint', max_length=255)),
                ('file_name', models.CharField(help_text='Имя файла', max_length=500)),
                ('article', models.CharField(blank=True, db_index=True, help_text='Артикул', max_length=100, null=True)),
                ('position', models.IntegerField(db_index=True, default=0, help_text='Позиция в очереди (0 = первое)')),
                ('estimated_time', models.IntegerField(default=0, help_text='Оценочное время печати (секунды)')),
                ('estimated_start', models.DateTimeField(blank=True, help_text='Расчетное время начала', null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text='Время добавления в очередь')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Время обновления')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Полные данные от API')),
            ],
            options={
                'verbose_name': 'Print Queue Item',
                'verbose_name_plural': 'Print Queue Items',
                'ordering': ['printer_id', 'position'],
                'indexes': [models.Index(fields=['printer_id', 'position'], name='simpleprint_printer_618b0d_idx'), models.Index(fields=['article'], name='simpleprint_article_da2b9f_idx')],
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, help_text='ID задания в SimplePrint', max_length=50, unique=True)),
                ('printer_id', models.CharField(db_index=True, help_text='ID принтера', max_length=50)),
                ('printer_name', models.CharField(help_text='Имя принтера', max_length=100)),
                ('file_id', models.CharField(blank=True, help_text='ID файла в SimplePrint', max_length=255, null=True)),
                ('file_name', models.CharField(help_text='Имя файла', max_length=500)),
                ('article', models.CharField(blank=True, db_index=True, help_text='Артикул (парсинг из имени)', max_length=100, null=True)),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('printing', 'Печатается'), ('completed', 'Завершено'), ('cancelled', 'Отменено'), ('failed', 'Ошибка')], db_index=True, help_text='Статус задания', max_length=20)),
                ('percentage', models.IntegerField(default=0, help_text='Процент выполнения (0-100)')),
                ('current_layer', models.IntegerField(default=0, help_text='Текущий слой')),
                ('max_layer', models.IntegerField(default=0, help_text='Максимальный слой')),
                ('queued_at', models.DateTimeField(blank=True, help_text='Время добавления в очередь', null=True)),
                ('started_at', models.DateTimeField(blank=True, db_index=True, help_text='Время начала печати', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Время завершения', null=True)),
                ('estimated_time', models.IntegerField(default=0, help_text='Оценочное время (секунды)')),
                ('elapsed_time', models.IntegerField(default=0, help_text='Затраченное время (секунды)')),
                ('success', models.BooleanField(default=False, help_text='Задание успешно завершено')),
                ('error_message', models.TextField(blank=True, help_text='Сообщение об ошибке')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Полные данные от API')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Время создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Время обновления записи')),
            ],
            options={
                'verbose_name': 'Print Job',
                'verbose_name_plural': 'Print Jobs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['printer_id', '-started_at'], name='simpleprint_printer_cae01e_idx'), models.Index(fields=['status', '-started_at'], name='simpleprint_status_e486b7_idx'), models.Index(fields=['article', '-started_at'], name='simpleprint_article_a27a90_idx'), models.Index(fields=['-completed_at'], name='simpleprint_complet_60ec95_idx')],
            },
        ),
        migrations.CreateModel(
            name='PrinterWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('printer_online', 'Принтер онлайн'), ('printer_offline', 'Принтер оффлайн'), ('job_started', 'Задание начато'), ('job_completed', 'Задание завершено'), ('job_cancelled', 'Задание отменено'), ('job_failed', 'Задание провалено'), ('job_progress', 'Прогресс задания'), ('queue_changed', 'Очередь изменена'), ('error_occurred', 'Произошла ошибка'), ('unknown', 'Неизвестное событие')], db_index=True, help_text='Тип события', max_length=50)),
                ('printer_id', models.CharField(blank=True, db_index=True, help_text='ID принтера', max_length=50, null=True)),
                ('job_id', models.CharField(blank=True, help_text='ID задания', max_length=50, null=True)),
                ('payload', models.JSONField(help_text='Полные данные webhook payload')),
                ('processed', models.BooleanField(db_index=True, default=False, help_text='Событие обработано')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Время обработки', null=True)),
                ('processing_error', models.TextField(blank=True, help_text='Ошибка при обработке')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Время получения webhook')),
            ],
            options={
                'verbose_name': 'Printer Webhook Event',
                'verbose_name_plural': 'Printer Webhook Events',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['printer_id', '-received_at'], name='simpleprint_printer_8887ff_idx'), models.Index(fields=['event_type', '-received_at'], name='simpleprint_event_t_594948_idx'), models.Index(fields=['processed', '-received_at'], name='simpleprint_process_209933_idx')],
            },
        ),
    ]
