# Generated by Django 4.2.7 on 2025-10-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleprint', '0006_alter_printerwebhookevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printerwebhookevent',
            name='event_type',
            field=models.CharField(choices=[('test', 'Тестовое событие'), ('printer_online', 'Принтер онлайн'), ('printer_offline', 'Принтер оффлайн'), ('printer_state_changed', 'Изменение состояния принтера'), ('job_started', 'Задание начато'), ('job_completed', 'Задание завершено'), ('job_cancelled', 'Задание отменено'), ('job_failed', 'Задание провалено'), ('job_paused', 'Задание приостановлено'), ('job_resumed', 'Задание возобновлено'), ('job_progress', 'Прогресс задания'), ('queue_changed', 'Очередь изменена'), ('queue_item_deleted', 'Элемент очереди удален'), ('file_created', 'Файл создан'), ('file_deleted', 'Файл удален'), ('filament_deleted', 'Филамент удален'), ('ai_failure_detected', 'AI обнаружил проблему'), ('ai_false_positive', 'AI ложное срабатывание'), ('error_occurred', 'Произошла ошибка'), ('unknown', 'Неизвестное событие')], db_index=True, help_text='Тип события', max_length=50),
        ),
    ]
