# Generated by Django 4.2.7 on 2025-08-13 19:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reserved_stock',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Количество товара в резерве', max_digits=10),
        ),
    ]
