# Generated by Django 4.2.7 on 2025-08-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_reserved_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, default='', help_text='Цвет товара из МойСклад', max_length=100),
        ),
    ]
