# Generated by Django 4.2.7 on 2025-07-21 21:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_new_product_stock', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Целевой остаток для новых товаров')),
                ('default_target_days', models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)], verbose_name='Целевой запас в днях для старых товаров')),
                ('low_stock_threshold', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Порог низкого остатка')),
                ('products_per_page', models.IntegerField(choices=[(25, '25'), (50, '50'), (100, '100'), (200, '200')], default=100, verbose_name='Товаров на странице')),
                ('show_images', models.BooleanField(default=True, verbose_name='Показывать изображения товаров')),
                ('auto_refresh_interval', models.IntegerField(choices=[(0, 'Отключено'), (30, '30 секунд'), (60, '1 минута'), (300, '5 минут'), (600, '10 минут')], default=0, verbose_name='Автообновление страницы (секунды)')),
            ],
            options={
                'verbose_name': 'Общие настройки',
                'verbose_name_plural': 'Общие настройки',
            },
        ),
        migrations.CreateModel(
            name='SyncScheduleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_enabled', models.BooleanField(default=True, verbose_name='Включить автоматическую синхронизацию')),
                ('sync_interval_minutes', models.IntegerField(choices=[(30, '30 минут'), (60, '1 час'), (90, '1,5 часа'), (120, '2 часа'), (150, '2,5 часа'), (180, '3 часа'), (210, '3,5 часа'), (240, '4 часа'), (270, '4,5 часа'), (300, '5 часов'), (360, '6 часов'), (420, '7 часов'), (480, '8 часов'), (540, '9 часов'), (600, '10 часов'), (660, '11 часов'), (720, '12 часов'), (1440, '24 часа')], default=60, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(1440)], verbose_name='Интервал синхронизации (минуты)')),
                ('warehouse_id', models.CharField(blank=True, max_length=36, verbose_name='ID склада для синхронизации')),
                ('warehouse_name', models.CharField(blank=True, max_length=255, verbose_name='Название склада')),
                ('excluded_group_ids', models.JSONField(blank=True, default=list, verbose_name='Исключаемые группы товаров (ID)')),
                ('excluded_group_names', models.JSONField(blank=True, default=list, verbose_name='Исключаемые группы товаров (названия)')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Время последней синхронизации')),
                ('last_sync_status', models.CharField(blank=True, choices=[('success', 'Успешно'), ('failed', 'Ошибка'), ('partial', 'Частично'), ('in_progress', 'В процессе')], max_length=20, verbose_name='Статус последней синхронизации')),
                ('last_sync_message', models.TextField(blank=True, verbose_name='Сообщение о последней синхронизации')),
                ('total_syncs', models.IntegerField(default=0, verbose_name='Всего синхронизаций')),
                ('successful_syncs', models.IntegerField(default=0, verbose_name='Успешных синхронизаций')),
            ],
            options={
                'verbose_name': 'Настройки синхронизации',
                'verbose_name_plural': 'Настройки синхронизации',
            },
        ),
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Информация о системе',
                'verbose_name_plural': 'Информация о системе',
            },
        ),
    ]
