# Generated by Django 4.2.7 on 2025-07-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncschedulesettings',
            name='schedule_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время создания/обновления расписания'),
        ),
    ]
